# Generated by Django 5.0.4 on 2024-07-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_num', models.CharField(max_length=100)),
                ('Asset_name', models.CharField(max_length=100)),
                ('Asset_type', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Item_code', models.CharField(max_length=100)),
                ('Assigned_To', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to=None)),
                ('Serial_number', models.CharField(max_length=100)),
                ('Model_number', models.CharField(max_length=100)),
                ('Machine_OS_configuration', models.CharField(max_length=100)),
                ('Movable_nonmovable', models.CharField(max_length=100)),
                ('Vender_Supplier', models.CharField(max_length=100)),
                ('Maintenance', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Year_of_purchasing', models.DateField()),
                ('Year_of_expiry', models.DateField()),
                ('Age_life', models.CharField(max_length=100)),
                ('Supporting_docs', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('Notes', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_num', models.CharField(max_length=100)),
                ('Category_type', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_num', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_num', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_num', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('loc_status', models.CharField(default='Active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_num', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='AssetOwner_Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_asset', models.BooleanField(default=False)),
                ('view_asset', models.BooleanField(default=False)),
                ('edit_asset', models.BooleanField(default=False)),
                ('delete_asset', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_mng.userdetails')),
            ],
        ),
    ]
