# Generated by Django 5.0.4 on 2024-07-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetowner_privilege',
            name='privilege_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assetowner_privilege',
            name='report_download',
            field=models.BooleanField(default=False),
        ),
    ]
