# Generated by Django 5.0.4 on 2024-07-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mng', '0003_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOwner_Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_asset', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_mng.userdetails')),
            ],
        ),
    ]
