# Generated by Django 5.0.4 on 2024-07-24 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mng', '0003_assetowner_privilege_add_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CISO_Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciso_add_asset', models.BooleanField(default=False)),
                ('ciso_view_asset', models.BooleanField(default=False)),
                ('ciso_edit_asset', models.BooleanField(default=False)),
                ('ciso_delete_asset', models.BooleanField(default=False)),
                ('ciso_privilege_update', models.BooleanField(default=False)),
                ('ciso_report_download', models.BooleanField(default=False)),
                ('ciso_add_user', models.BooleanField(default=False)),
                ('ciso_view_user', models.BooleanField(default=False)),
                ('ciso_edit_user', models.BooleanField(default=False)),
                ('ciso_delete_user', models.BooleanField(default=False)),
                ('ciso_add_employee', models.BooleanField(default=False)),
                ('ciso_view_employee', models.BooleanField(default=False)),
                ('ciso_edit_employee', models.BooleanField(default=False)),
                ('ciso_delete_employee', models.BooleanField(default=False)),
                ('ciso_add_location', models.BooleanField(default=False)),
                ('ciso_view_location', models.BooleanField(default=False)),
                ('ciso_edit_location', models.BooleanField(default=False)),
                ('ciso_delete_location', models.BooleanField(default=False)),
                ('ciso_add_department', models.BooleanField(default=False)),
                ('ciso_view_department', models.BooleanField(default=False)),
                ('ciso_edit_department', models.BooleanField(default=False)),
                ('ciso_delete_department', models.BooleanField(default=False)),
                ('ciso_add_category', models.BooleanField(default=False)),
                ('ciso_view_category', models.BooleanField(default=False)),
                ('ciso_edit_category', models.BooleanField(default=False)),
                ('ciso_delete_category', models.BooleanField(default=False)),
                ('ciso_add_roles', models.BooleanField(default=False)),
                ('ciso_view_roles', models.BooleanField(default=False)),
                ('ciso_edit_roles', models.BooleanField(default=False)),
                ('ciso_delete_roles', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_mng.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Head_Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_add_asset', models.BooleanField(default=False)),
                ('head_view_asset', models.BooleanField(default=False)),
                ('head_edit_asset', models.BooleanField(default=False)),
                ('head_delete_asset', models.BooleanField(default=False)),
                ('head_privilege_update', models.BooleanField(default=False)),
                ('head_report_download', models.BooleanField(default=False)),
                ('head_add_user', models.BooleanField(default=False)),
                ('head_view_user', models.BooleanField(default=False)),
                ('head_edit_user', models.BooleanField(default=False)),
                ('head_delete_user', models.BooleanField(default=False)),
                ('head_add_employee', models.BooleanField(default=False)),
                ('head_view_employee', models.BooleanField(default=False)),
                ('head_edit_employee', models.BooleanField(default=False)),
                ('head_delete_employee', models.BooleanField(default=False)),
                ('head_add_location', models.BooleanField(default=False)),
                ('head_view_location', models.BooleanField(default=False)),
                ('head_edit_location', models.BooleanField(default=False)),
                ('head_delete_location', models.BooleanField(default=False)),
                ('head_add_department', models.BooleanField(default=False)),
                ('head_view_department', models.BooleanField(default=False)),
                ('head_edit_department', models.BooleanField(default=False)),
                ('head_delete_department', models.BooleanField(default=False)),
                ('head_add_category', models.BooleanField(default=False)),
                ('head_view_category', models.BooleanField(default=False)),
                ('head_edit_category', models.BooleanField(default=False)),
                ('head_delete_category', models.BooleanField(default=False)),
                ('head_add_roles', models.BooleanField(default=False)),
                ('head_view_roles', models.BooleanField(default=False)),
                ('head_edit_roles', models.BooleanField(default=False)),
                ('head_delete_roles', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_mng.userdetails')),
            ],
        ),
    ]
