# Generated by Django 5.0.4 on 2024-07-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mng', '0004_assetowner_privilege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_num', models.CharField(max_length=100)),
                ('Asset_name', models.CharField(max_length=100)),
                ('Asset_type', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Item_code', models.CharField(max_length=100)),
                ('Assigned_To', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to=None)),
                ('Serial_number', models.CharField(max_length=100)),
                ('Model_number', models.CharField(max_length=100)),
                ('Machine_OS_configuration', models.CharField(max_length=100)),
                ('Movable_nonmovable', models.CharField(max_length=100)),
                ('Vender_Supplier', models.CharField(max_length=100)),
                ('Maintenance', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Year_of_purchasing', models.DateField()),
                ('Year_of_expiry', models.DateField()),
                ('Age_life', models.CharField(max_length=100)),
                ('Supporting_docs', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('Notes', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AssetTable',
        ),
    ]
